apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tomcat-8480
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      labels:
        k8s-app: tomcat-8480
    spec:
      containers:
      - image: 10.246.103.111/dev/tomcat-dev:vBUILD_NUMBER
        name : tomcat-8480
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-8480
  labels:
    k8s-app: tomcat-8480
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
    nodePort: 31111
  selector:
    k8s-app: tomcat-8480
